[package]
name = "swivel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.7", features = ["macros", ] }   # Replace with the actual version

actix-web = { version = "4.0" }  # Replace with the actual version
tokio = { version = "1.40.0", features = [ "rt-multi-thread" ]}
serde = { version = "1.0.210", features = ["derive"] }

[dev-dependencies]
http-body-util = "0.1.2"
tower = "0.5.1"
