[package]
name = "swivel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []

[dependencies]
axum = { version = "0.7", optional = true}   # Replace with the actual version

actix-web = { version = "4.0", optional = true }  # Replace with the actual version
