[package]
name = "anvil-liquid"
version = "0.1.0"
edition = "2021"

[dependencies]
liquid = "0.26.11"
anvil = { path = "../anvil" }
serde = { version = "1.0.219", features = ["derive"] }

[dev-dependencies]
tempfile = "3.15.0"


