[package]
name = "anvil-liquid"
version = "0.1.0"
edition = "2021"

[dependencies]
liquid = "0.26.11"
anvil = { path = "../anvil" }
serde = "1.0.219" 

[dev-dependencies]
tempfile = "3.15.0"

[dev-dependencies.serde]
version = "*"
features = ["derive"]

