[package]
name = "anvil-cli"
version = "0.1.0"
edition = "2021"
workspace = "../"

[dependencies]
askama = "0.12.1"
clap = { version = "4.5.23", features = ["derive"] }
heck = "0.5.0"
regex = "1.11.1"
anvil = { path = "../anvil" }
anvil_askama = { path = "../anvil-askama" }
