// Generated Model for {{ name }}
// This file is automatically generated

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct {{ name }} {
    pub id: String,
    {% for field in fields %}
    pub {{ field.name }}: {{ field.rust_type }},
    {% endfor %}
}

impl {{ name }} {
    pub fn new(
        id: String,
        {% for field in fields %}
        {{ field.name }}: {{ field.rust_type }},
        {% endfor %}
    ) -> Self {
        Self {
            id,
            {% for field in fields %}
            {{ field.name }},
            {% endfor %}
        }
    }
}
