// Router configuration
// Auto-generated by Anvil

use std::sync::Arc;

pub fn configure_router() -> Router {
    let mut router = Router::new();
    
    {% for route in routes %}
    // {{ route.method }} {{ route.path }}
    router.route("{{ route.path }}", {{ route.method|lower }}({{ route.handler }}));
    {% endfor %}
    
    router
}
