[package]
name = "anvil-tera"
version = "0.2.0"
edition = "2021"

[dependencies]
serde = "1.0.219" 
tera = "1.20.0"
anvil = { path = "../anvil" }

[dev-dependencies]
tempfile = "3.15.0"

[dev-dependencies.serde]
version = "*"
features = ["derive"]

