[package]
name = "anvil_tera"
version = "0.1.0"
edition = "2021"

[dependencies]
heck = "0.5.0"
anvil = { path = "../anvil" }
regex = "1.11.1"
tera = "1.20.0"
serde = { version = "1.0.217", features = [ "derive" ] } 
once_cell = "1.20.2"
