// Router configuration
// Auto-generated by Anvil

use std::sync::Arc;

pub fn configure_router() -> Router {
    let mut router = Router::new();
    
    
    // GET /users
    router.route("/users", get(get_users));
    
    // GET /users/:id
    router.route("/users/:id", get(get_user));
    
    // POST /users
    router.route("/users", post(create_user));
    
    
    router
}// Router configuration
// Auto-generated by Anvil

use std::sync::Arc;

pub fn configure_router() -> Router {
    let mut router = Router::new();
    
    
    // PUT /users/:id
    router.route("/users/:id", put(update_user));
    
    
    router
}