[package]
name = "anvil-askama"
version = "0.1.0"
edition = "2021"

[dependencies]
anvil = { path = "../anvil" }
askama = "0.12.1"
heck = "0.5.0"
thiserror = "2.0.9"

[dev-dependencies]
tempfile = "3.15.0"
